### ISSUE TITLE
Guide for install

### ISSUE THREAD

**Issue by d3lak** [ILikesCaviar/BDO_Enhancement_Tool#1]
Guide to run this? have installed with all modules still not working

**Comment by ILikesCaviar** [comment]
I'm not sure why this is, but it was missing some __init__ files. I was using a different repository earlier and didn't have time to test this one. If you pull the changes and use start_ui.py as your entry point it should work now.

**Comment by ILikesCaviar** [comment]
I also added the entry point above and some more info to the readme to help people get started. If there are any other problems please let me know what the terminal output or what is in the LOG file and I will try to debug it.
Thank you.

**Comment by d3lak** [comment]
Indeed it does work now. Thank you!
