### ISSUE TITLE
Steam authentication loops.

### ISSUE THREAD

**Issue by Arielore** [ILikesCaviar/BDO_Enhancement_Tool#11]
Do you test against steam authentication on PA site? When I get through the authentication process with email code on the steam passthrough site it doesn't pass back to PA page. It seems to loose the key and act like a fresh login attempt.

Its like this on both the old and new source.

**Comment by Arielore** [comment]
after steamauth gets all secret info and approves;
![image](https://user-images.githubusercontent.com/82731531/115132532-03b52700-9fb6-11eb-8f74-2308e4e2d695.png)

Disappointing fresh login to steam page, no cached info;
![image](https://user-images.githubusercontent.com/82731531/115132557-3eb75a80-9fb6-11eb-8722-abfdc3941e92.png)

**Comment by ILikesCaviar** [comment]
hmm, nope I don't have a steam account. This is the first time I've even considered that. I'm not sure what could be causing the loop since the web browser (chromium) should function normal at least. I'll have a look. It can be hard to make an exception for this kind of thing when I can't debug and/or look at the web traffic.

**Comment by Arielore** [comment]
It's not really a loop the steamguard page is just not working correctly. There is a lot of stuff passed to the steam page in browser sessions etc. but the page seems like a paranoid browser that just dumps any referrer, session, cookie or secret so it cant return to PA site or login to steam page. My bet is it needs a second profile to separately handle the steam page values as the add cookie event gets called several times but none of the steam cookies enter the cookie store.

Anyhow I am trying to use a simpler library for scraping 'urllib.request' and poking at the site to try and get authenticated. If that works I think the PA session cookies can be passed into your existing code.

**Comment by ILikesCaviar** [comment]
Wait you said you were using anaconda right? I had an issue where the QtWebEngine was not working right (specifically with the cookie store) on the anaconda Qt packages. I had to remove them and install PyQt5 and QtWebEngine using pip to get the up-to-date ones. Maybe this will fix it?

**Comment by Arielore** [comment]
I got rid of anaconda caches and started with a fresh copy of the recommended interpreter. There is something odd about pyqt5 as it took several cycles of installing and uninstalling pip, pyqt5 and QtWebEngine to get everything to build. But once it did build it has worked perfectly, so far ;)

Steam works if those libraries are installed right. 
Thanks for your time!

I think 'militia' weapons are doing something funny in primary spot. But market is solid for me now.
'Item is not on the market'
'Critical Message: Error contacting central market'

**Comment by ILikesCaviar** [comment]
> I think 'militia' weapons are doing something funny in primary spot. But market is solid for me now.
> 'Item is not on the market'
> 'Critical Message: Error contacting central market'

Which militia weapon? Describe how you got the error. If you can reproduce the error go to File->Open Settings Directory and post you settings file

**Comment by Arielore** [comment]
It was the vitaclari but I don't trust my build at all.
