### ISSUE TITLE
No cost and not working margin

### ISSUE THREAD

**Issue by Glement** [ILikesCaviar/BDO_Enhancement_Tool#13]
When adding reblath +14 ( target +15)
and grunil as fs gear
urughons as equipment gear
and creating new custom strategy with target +99 fs  ( for pen attempts )
and setting crons for 99999999 so not to use them
app does not count 
![image](https://user-images.githubusercontent.com/33545106/131543291-f2c5f59a-f326-4b28-98b2-e68b58c555b2.png)
![image](https://user-images.githubusercontent.com/33545106/131543385-f9b67265-9853-4b37-9360-0bb754749317.png)

**Comment by ILikesCaviar** [comment]
Doesn't count?

**Comment by Graveflo** [comment]
closed, inactivity
