### ISSUE TITLE
Unable to start ui

### ISSUE THREAD

**Issue by IIPoliII** [ILikesCaviar/BDO_Enhancement_Tool#2]
Hello i am pretty new,

I am unable to start the app using the basic installer so now i am unsure if i need to install the modules of python.

So do i need to install something else even when i use the installer ?

Thanks 

EDIT : when i run it manually i get this 
![image](https://user-images.githubusercontent.com/29628512/56200257-b60c2980-603e-11e9-8a14-9997296bb665.png)

**Comment by ILikesCaviar** [comment]
Hello there! Sorry you are having this problem. I am not sure what is wrong but lets check some things.

The installer should package everything you need to run the program on a modern computer. The start_ui.exe file is not a python file. Try running start_ui.exe on its own. There should be a start menu or desktop icon if you chose to create them which will launch the program the intended way.

Python is made to interpret python code (conventionally with a *.py extension - text content) or compiled python code (conventionally with a *.pyc extension - bytecode content). Downloading the source code will give you *.py files that you can run with python.exe. Downloading the installer should give you start_ui.exe that runs by itself.

Hopefully this fixes the issue. Let me know if the problem persists.

**Comment by ILikesCaviar** [comment]
Since it has been a week I am closing this issue.
I believe from the image provided that the release executable was not being launched properly.
