### ISSUE TITLE
[Enhancement]Would like to see that works also on MENA 

### ISSUE THREAD

**Issue by ashkan90** [ILikesCaviar/BDO_Enhancement_Tool#4]
Hi, I've just want to calculate something clearly with this tool but as i can see that there's no support to MENA server. 
I'll really appreciated if you implement it too so i'll drop the [MP link](http://trade.tr.playblackdesert.com/) of MENA and hopefully you can make us happy to :)

**Comment by ashkan90** [comment]
> On the "Materials / Settings" tab there is a button "MP: Update Costs"
> On the "FS Gear" tab there is a button "MP: Update all"
> On the "Equipment" tab there is a button "MP: Update Base Cost"
> 
> The status bar at the bottom of the main window should say something when it recognizes a response from the server.
> Please check to make sure the prices updates correctly. A good test would be to check the black stones costs and maybe an armor/weapon or two. Prices will only update every 30 minutes even if you press the buttons.

Okay i tried these but button is disabled even if i registered to server., I cannot update mp prices actually.

**Comment by ILikesCaviar** [comment]
Check if the MENA domain works on the new version. There is an option at the bottom of the settings tab called "Market Domain." Try: trade.tr.playblackdesert.com
