### ISSUE TITLE
Question about running this

### ISSUE THREAD

**Issue by its-fel** [ILikesCaviar/BDO_Enhancement_Tool#5]
I apologize for the nooby question but frankly I have not been able to figure out how to build/run this. I have anaconda which you recommended but even after messing around myself I still haven't been able to stumble across how to run it so if you could give me a quick run through I'd deeply appreciate it.

**Comment by ILikesCaviar** [comment]
Sure, if you followed everything in the [REAME.md](https://github.com/ILikesCaviar/BDO_Enhancement_Tool#how-run-code) and you tried running:
`python.exe -m BDO_Enhancement_Tool`

Let me know the console output so I can tell you what is going wrong.

You may get something like this:
`python.exe: No module named BDO_Enhancement_Tool`

If this is the case you need to make sure the module (the directory containing the project) is in your pathon path environment variable. To do this find your python installation directory and look for a folder called "Lib" and inside the "site-packages" directory. The site-packages folder should automatically be in the python path variable. You can move the project folder here or make a text file here containing the path housing the project folder. In the case of the text file make sure the path is not pointing to the project's root folder but it's parent directory. This way the module name "BDO_Enhancement_Tool" matches a directory located in the python path. Make sure the text file has the extension '.pth' so the python interpreter knows that it is a path extension instruction.

**Comment by its-fel** [comment]
I sorted out the environment variable error and now I am left with this error message. Any advice?
![ccc8cc265f0a49b3d4b80933596f8ce2](https://user-images.githubusercontent.com/51485367/93052783-c27e2280-f634-11ea-9f0d-2992c07f1f7a.png)

**Comment by ILikesCaviar** [comment]
Your python environment is missing the fuzzywuzzy package. The list of dependencies is in the requirements.txt file. To install all of the dependencies, navigate to the root directory of the project and run:
`python.exe -m pip install -r requirements.txt`

**Comment by ILikesCaviar** [comment]
Actually, it just occurred to me this might be bad advice because the requirements.txt is meant for a fresh python install not over top an anaconda install. Anaconda uses it's own Qt packages.

just run:
`python.exe -m pip install fuzzywuzzy`

and try running the tool again. This should happen a few more times with some other packages that need to be installed. Just do the same thing for them to install the dependencies one by one.

**Comment by its-fel** [comment]
> Actually, it just occurred to me this might be bad advice because the requirements.txt is meant for a fresh python install not over top an anaconda install. Anaconda uses it's own Qt packages.
> 
> just run:
> `python.exe -m pip install fuzzywuzzy`
> 
> and try running the tool again. This should happen a few more times with some other packages that need to be installed. Just do the same thing for them to install the dependencies one by one.

This fixed my issues, thank you!

**Comment by ILikesCaviar** [comment]
No problem
