### ISSUE TITLE
Open Guide Overlay not working

### ISSUE THREAD

**Issue by superpal10** [ILikesCaviar/BDO_Enhancement_Tool#8]
On the latest beta version the Open Guide Overlay is not working.

**Comment by ILikesCaviar** [comment]
Hi, thanks for reporting this bug.

Does a message pop up on the main window when you click the button? Does it crash?

Go to File->Open Settings File Directory
and File->Open Log File

Send these to me if you can. (post here or discord Graveflo#6753, or email rammcconnell@gmail.com)

**Comment by ILikesCaviar** [comment]
This issue should be fixed now
